/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tutor_CONSTANTS_H
#define tutor_CONSTANTS_H

#include "tutor_types.h"

namespace tutorial {

class tutorConstants {
 public:
  tutorConstants();

  int32_t INT32CONSTANT;
  std::map<std::string, std::string>  MAPCONSTANT;
};

extern const tutorConstants g_tutor_constants;

} // namespace

#endif
